version: '3.8'

services:
  auth_server:
    image: auth_server
    container_name: auth_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - auth_server_data:/app/data
    env_file: 
      - dsas.env
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  auth_server_data:
