# lang_dict.py
LANGUAGES = {
    'en': {
        'title': 'Login to the system',
        'username_placeholder': 'Username',
        'password_placeholder': 'Password',
        'login_button': 'Login',
        'error_message': 'Invalid username or password',
        'user_exists': 'User already exists:',
        'user_added': 'User added successfully:',
        'user_deleted': 'User deleted successfully:',
        'user_not_found': 'User not found:',
        'password_updated': 'Password updated successfully:',
        'user_list': 'List of users:',
        'no_users': 'No users found.',
        'usage': 'Usage:\n  Add user: python manage.py add <username> <password>\n  Delete user: python manage.py delete <username>\n  Update password: python manage.py update <username> <new_password>\n  List users: python manage.py list',
        'invalid_args': 'Invalid arguments provided.'
    },
    'ru': {
        'title': 'Вход в систему',
        'username_placeholder': 'Имя пользователя',
        'password_placeholder': 'Пароль',
        'login_button': 'Войти',
        'error_message': 'Неверные учетные данные. Пожалуйста, попробуйте снова.',
        'user_exists': 'Пользователь уже существует:',
        'user_added': 'Пользователь успешно добавлен:',
        'user_deleted': 'Пользователь успешно удален:',
        'user_not_found': 'Пользователь не найден:',
        'password_updated': 'Пароль успешно обновлен:',
        'user_list': 'Список пользователей:',
        'no_users': 'Список пользователей пуст.',
        'usage': 'Использование:\n  Добавить пользователя: python manage.py add <username> <password>\n  Удалить пользователя: python manage.py delete <username>\n  Обновить пароль: python manage.py update <username> <new_password>\n  Список пользователей: python manage.py list',
        'invalid_args': 'Неверные аргументы.'
    },
    'imperial_ru': {
        'title': 'Вход в систему',
        'username_placeholder': 'Ваше имя',
        'password_placeholder': 'Ваш пароль',
        'login_button': 'Входить',
        'error_message': 'Неверные данные для входа. Попробуйте вновь.',
        'user_exists': 'Данный пользователь уже существует:',
        'user_added': 'Пользователь был успешно добавлен:',
        'user_deleted': 'Пользователь был успешно удалён:',
        'user_not_found': 'Пользователь не был найден:',
        'password_updated': 'Пароль пользователя был успешно обновлён:',
        'user_list': 'Список всех пользователей:',
        'no_users': 'Пользователей пока нет.',
        'usage': 'Инструкция:\n  Добавить пользователя: python manage.py add <имя> <пароль>\n  Удалить пользователя: python manage.py delete <имя>\n  Обновить пароль: python manage.py update <имя> <новый_пароль>\n  Список пользователей: python manage.py list',
        'invalid_args': 'Ошибка в аргументах.'
    },
   'soviet_ru': {
        'title': 'Вход в систему, товарищ!',
        'username_placeholder': 'Товарищ, введите имя',
        'password_placeholder': 'Пароль (секретный)',
        'login_button': 'Войти в систему',
        'error_message': 'Товарищ, неверные учетные данные! Попробуйте еще раз.',
        'user_exists': 'Товарищ, этот пользователь уже есть:',
        'user_added': 'Товарищ, пользователь успешно добавлен:',
        'user_deleted': 'Товарищ, пользователь успешно удалён:',
        'user_not_found': 'Товарищ, пользователь не найден:',
        'password_updated': 'Товарищ, пароль обновлён:',
        'user_list': 'Товарищ, вот список пользователей:',
        'no_users': 'Товарищ, пользователей пока нет.',
        'usage': 'Использование:\n  Добавить пользователя: python manage.py add <имя> <пароль>\n  Удалить пользователя: python manage.py delete <имя>\n  Обновить пароль: python manage.py update <имя> <новый_пароль>\n  Список пользователей: python manage.py list',
        'invalid_args': 'Товарищ, аргументы неверны.'
    },
    'redneck_us': {
        'title': 'Y’all, log on in!',
        'username_placeholder': 'Whatcha go by?',
        'password_placeholder': 'Secret pass',
        'login_button': 'Git ‘er done!',
        'error_message': 'Dang it, wrong name or pass. Try agin, buddy.',
        'user_exists': 'Shoot! User already exists:',
        'user_added': 'Well, user added just fine:',
        'user_deleted': 'Yup, user deleted:',
        'user_not_found': 'Can’t find that user, pal:',
        'password_updated': 'Alright, password’s updated:',
        'user_list': 'Here’s the list of folks:',
        'no_users': 'Ain’t no users here yet.',
        'usage': 'How-to:\n  Add a user: python manage.py add <username> <password>\n  Delete a user: python manage.py delete <username>\n  Update password: python manage.py update <username> <new_password>\n  List users: python manage.py list',
        'invalid_args': 'Whoa there! Those args ain’t right.'
    },
    'irish_gang': {
        'title': 'Login, ya lad!',
        'username_placeholder': 'What’s yer name, mate?',
        'password_placeholder': 'Yer code, quick!',
        'login_button': 'Get inside, quick!',
        'error_message': 'Oi! Wrong name or code. Try it again, mate.',
        'user_exists': 'Listen, that user’s already here:',
        'user_added': 'Right, user’s been added:',
        'user_deleted': 'Alright, user’s gone now:',
        'user_not_found': 'Can’t find that user, mate:',
        'password_updated': 'Password’s sorted for ya, mate:',
        'user_list': 'Here’s the lot:',
        'no_users': 'No users yet, lad.',
        'usage': 'Instructions:\n  Add a user: python manage.py add <username> <password>\n  Delete a user: python manage.py delete <username>\n  Update password: python manage.py update <username> <new_password>\n  List users: python manage.py list',
        'invalid_args': 'Ah, you’ve botched the arguments, mate.'
    },
    'fr': {
        'title': 'Connexion au système',
        'username_placeholder': 'Nom d’utilisateur',
        'password_placeholder': 'Mot de passe',
        'login_button': 'Se connecter',
        'error_message': "Nom d'utilisateur ou mot de passe invalide.",
        'user_exists': "L'utilisateur existe déjà :",
        'user_added': "Utilisateur ajouté avec succès :",
        'user_deleted': "Utilisateur supprimé avec succès :",
        'user_not_found': "Utilisateur introuvable :",
        'password_updated': "Mot de passe mis à jour avec succès :",
        'user_list': "Liste des utilisateurs :",
        'no_users': "Aucun utilisateur trouvé.",
        'usage': "Utilisation :\n  Ajouter un utilisateur : python manage.py add <nom_utilisateur> <mot_de_passe>\n  Supprimer un utilisateur : python manage.py delete <nom_utilisateur>\n  Mettre à jour le mot de passe : python manage.py update <nom_utilisateur> <nouveau_mot_de_passe>\n  Liste des utilisateurs : python manage.py list",
        'invalid_args': "Arguments invalides fournis."
    },
    'de': {
        'title': 'Anmeldung im System',
        'username_placeholder': 'Benutzername',
        'password_placeholder': 'Passwort',
        'login_button': 'Einloggen',
        'error_message': 'Ungültiger Benutzername oder Passwort.',
        'user_exists': 'Benutzer existiert bereits:',
        'user_added': 'Benutzer erfolgreich hinzugefügt:',
        'user_deleted': 'Benutzer erfolgreich gelöscht:',
        'user_not_found': 'Benutzer nicht gefunden:',
        'password_updated': 'Passwort erfolgreich aktualisiert:',
        'user_list': 'Benutzerliste:',
        'no_users': 'Keine Benutzer gefunden.',
        'usage': 'Verwendung:\n  Benutzer hinzufügen: python manage.py add <benutzername> <passwort>\n  Benutzer löschen: python manage.py delete <benutzername>\n  Passwort aktualisieren: python manage.py update <benutzername> <neues_passwort>\n  Benutzer auflisten: python manage.py list',
        'invalid_args': 'Ungültige Argumente angegeben.'
    },
    'es': {
        'title': 'Inicio de sesión en el sistema',
        'username_placeholder': 'Nombre de usuario',
        'password_placeholder': 'Contraseña',
        'login_button': 'Iniciar sesión',
        'error_message': 'Nombre de usuario o contraseña inválidos.',
        'user_exists': 'El usuario ya existe:',
        'user_added': 'Usuario agregado con éxito:',
        'user_deleted': 'Usuario eliminado con éxito:',
        'user_not_found': 'Usuario no encontrado:',
        'password_updated': 'Contraseña actualizada con éxito:',
        'user_list': 'Lista de usuarios:',
        'no_users': 'No se encontraron usuarios.',
        'usage': 'Uso:\n  Agregar usuario: python manage.py add <nombre_de_usuario> <contraseña>\n  Eliminar usuario: python manage.py delete <nombre_de_usuario>\n  Actualizar contraseña: python manage.py update <nombre_de_usuario> <nueva_contraseña>\n  Listar usuarios: python manage.py list',
        'invalid_args': 'Argumentos inválidos proporcionados.'
    },
    'it': {
        'title': 'Accesso al sistema',
        'username_placeholder': 'Nome utente',
        'password_placeholder': 'Password',
        'login_button': 'Accedi',
        'error_message': 'Nome utente o password non validi.',
        'user_exists': "L'utente esiste già:",
        'user_added': 'Utente aggiunto con successo:',
        'user_deleted': 'Utente eliminato con successo:',
        'user_not_found': 'Utente non trovato:',
        'password_updated': 'Password aggiornata con successo:',
        'user_list': 'Elenco degli utenti:',
        'no_users': 'Nessun utente trovato.',
        'usage': 'Utilizzo:\n  Aggiungere un utente: python manage.py add <nome_utente> <password>\n  Eliminare un utente: python manage.py delete <nome_utente>\n  Aggiornare la password: python manage.py update <nome_utente> <nuova_password>\n  Elenco degli utenti: python manage.py list',
        'invalid_args': 'Argomenti non validi forniti.'
    },
    'zh': {
        'title': '登录系统',
        'username_placeholder': '用户名',
        'password_placeholder': '密码',
        'login_button': '登录',
        'error_message': '用户名或密码无效。',
        'user_exists': '用户已存在：',
        'user_added': '用户已成功添加：',
        'user_deleted': '用户已成功删除：',
        'user_not_found': '找不到用户：',
        'password_updated': '密码已成功更新：',
        'user_list': '用户列表：',
        'no_users': '未找到用户。',
        'usage': '用法：\n  添加用户：python manage.py add <用户名> <密码>\n  删除用户：python manage.py delete <用户名>\n  更新密码：python manage.py update <用户名> <新密码>\n  列出用户：python manage.py list',
        'invalid_args': '提供的参数无效。'
    }
}

def get_language(lang_code='en'):
    return LANGUAGES.get(lang_code, LANGUAGES['en'])
